# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d78557cb35a0f880c6854f7fcbd3731643bb56b4a7636b6a99b2388187e293bf0c2a14f138791890d0e938e7c16bcd19a0e290a4e3933ce50bc99c17af680f04

test:
  secret_key_base: 4205148d28aff3b7c165215533782a269fdb56361202864006f6a118f32bd78ba2dd919735def91b5bf334c380e6e9fc09cb6bd9c5243f8e8b89de47d186ba1d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
